unit Main;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms, Dialogs, StdCtrls, RSPrint;

type
  TFrmMain = class(TForm)
    btnPreview: TButton;
    RSPrint: TRSPrinter;
    btnPrint: TButton;
    cmbMode: TComboBox;
    lblMode: TLabel;
    procedure btnPreviewClick(Sender: TObject);
    procedure btnPrintClick(Sender: TObject);

  private
    procedure GenerateData;
    procedure PrintHeader;
    procedure LoadNames(nameList: TStringList);

  end;

var
  FrmMain: TFrmMain;

implementation

uses
  RSPrint.CommonTypes;

{$R *.dfm}

procedure TFrmMain.btnPreviewClick(Sender: TObject);
begin
  GenerateData;
  RSPrint.PreviewReal;
end;

procedure TFrmMain.btnPrintClick(Sender: TObject);
begin
  GenerateData;
  RSPrint.PrintAll;
end;

procedure TFrmMain.GenerateData;
var
  Counter: Integer;
  CurrentLine: Integer;
  NameList: TStringList;
  Name: string;
begin
  NameList := TStringList.Create;
  try
    LoadNames(NameList);

    RSPrint.Mode := TPrinterMode(cmbMode.ItemIndex);
    RSPrint.ReportName := 'RSPrint Demo App';

    RSPrint.BeginDoc;

    PrintHeader;
    CurrentLine := 5;

    Counter := 0;
    for Name in NameList do
    begin
      Counter := Counter + 1;

      RSPrint.Write(CurrentLine,  1, Format('%4.4d', [Counter]));
      RSPrint.Write(CurrentLine, 10, Name);

      CurrentLine := CurrentLine + 1;

      if CurrentLine > RSPrint.Lines then
      begin
        RSPrint.NewPage;
        PrintHeader;
        CurrentLine := 5;
      end;
    end;
  finally
    NameList.Free;
  end;
end;

procedure TFrmMain.LoadNames(nameList: TStringList);
begin
  nameList.Add('Amy Acker');
  nameList.Add('Candice Accola');
  nameList.Add('Amy Adams');
  nameList.Add('Edie Adams');
  nameList.Add('Jane Adams');
  nameList.Add('Joey Lauren Adams');
  nameList.Add('Julie Adams');
  nameList.Add('Shohreh Aghdashloo');
  nameList.Add('Dianna Agron');
  nameList.Add('Christina Aguilera');
  nameList.Add('Jessica Alba');
  nameList.Add('Jane Alexander');
  nameList.Add('Khandi Alexander');
  nameList.Add('Sasha Alexander');
  nameList.Add('Tatyana Ali');
  nameList.Add('Debbie Allen');
  nameList.Add('Elizabeth Allen');
  nameList.Add('Joan Allen');
  nameList.Add('Karen Allen');
  nameList.Add('Krista Allen');
  nameList.Add('Laura Allen');
  nameList.Add('Nancy Allen');
  nameList.Add('Kirstie Alley');
  nameList.Add('June Allyson');
  nameList.Add('Trini Alvarado');
  nameList.Add('Lauren Ambrose');
  nameList.Add('Mädchen Amick');
  nameList.Add('Suzy Amis');
  nameList.Add('Andrea Anders');
  nameList.Add('Gillian Anderson');
  nameList.Add('Loni Anderson');
  nameList.Add('Melody Anderson');
  nameList.Add('Nicole Anderson');
  nameList.Add('Jennifer Aniston');
  nameList.Add('Susan Anton');
  nameList.Add('Christina Applegate');
  nameList.Add('Anne Archer');
  nameList.Add('Beverly Archer');
  nameList.Add('Eve Arden');
  nameList.Add('Ashley Argota');
  nameList.Add('Jillian Armenante');
  nameList.Add('Bess Armstrong');
  nameList.Add('Patricia Arquette');
  nameList.Add('Rosanna Arquette');
  nameList.Add('Bea Arthur');
  nameList.Add('Jean Arthur');
  nameList.Add('Elizabeth Ashley');
  nameList.Add('Mary Astor');
  nameList.Add('Margaret Avery');
  nameList.Add('Candice Azzara');
  nameList.Add('Lauren Bacall');
  nameList.Add('Barbara Bach');
  nameList.Add('Catherine Bach');
  nameList.Add('Mary Badham');
  nameList.Add('Pearl Bailey');
  nameList.Add('Fay Bainter');
  nameList.Add('Kathy Baker');
  nameList.Add('Fairuza Balk');
  nameList.Add('Lucille Ball');
  nameList.Add('Anne Bancroft');
  nameList.Add('Elizabeth Banks');
  nameList.Add('Tyra Banks');
  nameList.Add('Christine Baranski');
  nameList.Add('Adrienne Barbeau');
  nameList.Add('Ellen Barkin');
  nameList.Add('Priscilla Barnes');
  nameList.Add('Majel Barrett');
  nameList.Add('Barbara Barrie');
  nameList.Add('Drew Barrymore');
  nameList.Add('Ethel Barrymore');
  nameList.Add('Roseanne Barr');
  nameList.Add('Mischa Barton');
  nameList.Add('Kim Basinger');
  nameList.Add('Angela Bassett');
  nameList.Add('Kathy Bates');
  nameList.Add('Cyia Batten');
  nameList.Add('Anne Baxter');
  nameList.Add('Jennifer Beals');
  nameList.Add('Amanda Bearse');
  nameList.Add('Kimberly Beck');
  nameList.Add('Bonnie Bedelia');
  nameList.Add('Barbara Bel Geddes');
  nameList.Add('Catherine Bell');
  nameList.Add('Kristen Bell');
  nameList.Add('Lake Bell');
  nameList.Add('Camilla Belle');
  nameList.Add('Maria Bello');
  nameList.Add('Andrea Bendewald');
  nameList.Add('Annette Bening');
  nameList.Add('Amber Benson');
  nameList.Add('Julie Benz');
  nameList.Add('Candice Bergen');
  nameList.Add('Elizabeth Berkley');
  nameList.Add('Jeannie Berlin');
  nameList.Add('Crystal Bernard');
  nameList.Add('Sandra Bernhard');
  nameList.Add('Halle Berry');
  nameList.Add('Valerie Bertinelli');
  nameList.Add('Angela Bettis');
  nameList.Add('Troy Beyer');
  nameList.Add('Leslie Bibb');
  nameList.Add('Jessica Biel');
  nameList.Add('Rachel Bilson');
  nameList.Add('Thora Birch');
  nameList.Add('Kerry Bishé');
  nameList.Add('Summer Bishil');
  nameList.Add('Karen Black');
  nameList.Add('Betsy Blair');
  nameList.Add('Linda Blair');
  nameList.Add('Selma Blair');
  nameList.Add('Ronee Blakley');
  nameList.Add('Jolene Blalock');
  nameList.Add('Tammy Blanchard');
  nameList.Add('Alexis Bledel');
  nameList.Add('Yasmine Bleeth');
  nameList.Add('Joan Blondell');
  nameList.Add('Nikki Blonsky');
  nameList.Add('Moon Bloodgood');
  nameList.Add('Ann Blyth');
  nameList.Add('Eleanor Boardman');
  nameList.Add('Mary Boland');
  nameList.Add('Julia Bond');
  nameList.Add('Beulah Bondi');
  nameList.Add('Lisa Bonet');
  nameList.Add('Shirley Booth');
  nameList.Add('Olive Borden');
  nameList.Add('Rachel Boston');
  nameList.Add('Kate Bosworth');
  nameList.Add('Clara Bow');
  nameList.Add('Katrina Bowden');
  nameList.Add('Andrea Bowen');
  nameList.Add('Julie Bowen');
  nameList.Add('Lara Flynn Boyle');
  nameList.Add('Lorraine Bracco');
  nameList.Add('Alice Brady');
  nameList.Add('Alexandra Breckenridge');
  nameList.Add('Eileen Brennan');
  nameList.Add('Amy Brenneman');
  nameList.Add('Abigail Breslin');
  nameList.Add('Jordana Brewster');
  nameList.Add('Connie Britton');
  nameList.Add('Jayne Brook');
  nameList.Add('Geraldine Brooks');
  nameList.Add('Louise Brooks');
  nameList.Add('Blair Brown');
  nameList.Add('Yvette Nicole Brown');
  nameList.Add('Leslie Browne');
  nameList.Add('Sabrina Bryan');
  nameList.Add('Joy Bryant');
  nameList.Add('Tara Buck');
  nameList.Add('Betty Buckley');
  nameList.Add('Sandra Bullock');
  nameList.Add('Billie Burke');
  nameList.Add('Delta Burke');
  nameList.Add('Carol Burnett');
  nameList.Add('Catherine Burns');
  nameList.Add('Ellen Burstyn');
  nameList.Add('Hilarie Burton');
  nameList.Add('Sophia Bush');
  nameList.Add('Brett Butler');
  nameList.Add('Yancy Butler');
  nameList.Add('Spring Byington');
  nameList.Add('Amanda Bynes');
  nameList.Add('Marion Byron');
  nameList.Add('Tisha Campbell');
  nameList.Add('Dyan Cannon');
  nameList.Add('Lizzy Caplan');
  nameList.Add('Kate Capshaw');
  nameList.Add('Irene Cara');
  nameList.Add('Linda Cardellini');
  nameList.Add('Lynn Carlin');
  nameList.Add('Kitty Carlisle');
  nameList.Add('Sue Carol');
  nameList.Add('Charisma Carpenter');
  nameList.Add('Jennifer Carpenter');
  nameList.Add('Barbara Carrera');
  nameList.Add('Tia Carrere');
  nameList.Add('Lynda Carter');
  nameList.Add('Diahann Carroll');
  nameList.Add('Madeline Carroll');
  nameList.Add('Nancy Carroll');
  nameList.Add('Peggy Cass');
  nameList.Add('Joanna Cassidy');
  nameList.Add('Katie Cassidy');
  nameList.Add('Phoebe Cates');
  nameList.Add('Jessica Cauffiel');
  nameList.Add('Emma Caulfield');
  nameList.Add('Lacey Chabert');
  nameList.Add('Sarah Chalke');
  nameList.Add('Carol Channing');
  nameList.Add('Stockard Channing');
  nameList.Add('Cyd Charisse');
  nameList.Add('Jessica Chastain');
  nameList.Add('Ruth Chatterton');
  nameList.Add('Kristin Chenoweth');
  nameList.Add('Cher');
  nameList.Add('Vanessa Lee Chester');
  nameList.Add('Anna Chlumsky');
  nameList.Add('Claudia Christian');
  nameList.Add('Erika Christensen');
  nameList.Add('Candy Clark');
  nameList.Add('Melinda Clarke');
  nameList.Add('Sarah Clarke');
  nameList.Add('Patricia Clarkson');
  nameList.Add('Jill Clayburgh');
  nameList.Add('Glenn Close');
  nameList.Add('Claudette Colbert');
  nameList.Add('Holliston Coleman');
  nameList.Add('Kim Coles');
  nameList.Add('Lynn Collins');
  nameList.Add('Holly Marie Combs');
  nameList.Add('Betty Compson');
  nameList.Add('Jennifer Connelly');
  nameList.Add('Rachael Leigh Cook');
  nameList.Add('Jennifer Coolidge');
  nameList.Add('Ellen Corby');
  nameList.Add('Miranda Cosgrove');
  nameList.Add('Courteney Cox');
  nameList.Add('Nikki Cox');
  nameList.Add('Yvonne Craig');
  nameList.Add('Jeanne Crain');
  nameList.Add('Joan Crawford');
  nameList.Add('Cathy Lee Crosby');
  nameList.Add('Denise Crosby');
  nameList.Add('Mary Crosby');
  nameList.Add('Marcia Cross');
  nameList.Add('Lindsay Crouse');
  nameList.Add('Suzanne Cryer');
  nameList.Add('Quinn Cummings');
  nameList.Add('Jane Curtin');
  nameList.Add('Jamie Lee Curtis');
  nameList.Add('Ann Cusack');
  nameList.Add('Joan Cusack');
  nameList.Add('Tawny Cypress');
  nameList.Add('Miley Cyrus');
  nameList.Add('Alexandra Daddario');
  nameList.Add('Dorothy Dandridge');
  nameList.Add('Claire Danes');
  nameList.Add('Beverly DAngelo');
  nameList.Add('Brittany Daniel');
  nameList.Add('Bebe Daniels');
  nameList.Add('Erin Daniels');
  nameList.Add('Blythe Danner');
  nameList.Add('Lisa Darr');
  nameList.Add('Jane Darwell');
  nameList.Add('Stacey Dash');
  nameList.Add('Ann B. Davis');
  nameList.Add('Bette Davis');
  nameList.Add('Dana Davis');
  nameList.Add('Geena Davis');
  nameList.Add('Hope Davis');
  nameList.Add('Kristin Davis');
  nameList.Add('Viola Davis');
  nameList.Add('Nancy Davis Reagan');
  nameList.Add('Pam Dawber');
  nameList.Add('Rosario Dawson');
  nameList.Add('Roxann Dawson');
  nameList.Add('Doris Day');
  nameList.Add('Marceline Day');
  nameList.Add('Priscilla Dean');
  nameList.Add('Yvonne De Carlo');
  nameList.Add('Ruby Dee');
  nameList.Add('Sandra Dee');
  nameList.Add('Ellen DeGeneres');
  nameList.Add('Kim Delaney');
  nameList.Add('Diane Delano');
  nameList.Add('Dana Delany');
  nameList.Add('Julie Delpy');
  nameList.Add('Rebecca De Mornay');
  nameList.Add('Carol Dempster');
  nameList.Add('Lori Beth Denberg');
  nameList.Add('Kat Dennings');
  nameList.Add('Sandy Dennis');
  nameList.Add('Bo Derek');
  nameList.Add('Laura Dern');
  nameList.Add('Portia de Rossi');
  nameList.Add('Donna DErrico');
  nameList.Add('Emily Deschanel');
  nameList.Add('Zooey Deschanel');
  nameList.Add('Amanda Detmer');
  nameList.Add('Loretta Devine');
  nameList.Add('Joyce DeWitt');
  nameList.Add('Susan Dey');
  nameList.Add('Cameron Diaz');
  nameList.Add('Angie Dickinson');
  nameList.Add('Marlene Dietrich');
  nameList.Add('Victoria Dillard');
  nameList.Add('Melinda Dillon');
  nameList.Add('Mia Dillon');
  nameList.Add('Donna Dixon');
  nameList.Add('Ellen Drew');
  nameList.Add('Megan Dodds');
  nameList.Add('Shannen Doherty');
  nameList.Add('Ami Dolenz');
  nameList.Add('Elisa Donovan');
  nameList.Add('Illeana Douglas');
  nameList.Add('Billie Dove');
  nameList.Add('Doris Dowling');
  nameList.Add('Rachel Dratch');
  nameList.Add('Fran Drescher');
  nameList.Add('Louise Dresser');
  nameList.Add('Marie Dressler');
  nameList.Add('Julia Louis-Dreyfus');
  nameList.Add('Alice Drummond');
  nameList.Add('Hilary Duff');
  nameList.Add('Olympia Dukakis');
  nameList.Add('Patty Duke');
  nameList.Add('Faye Dunaway');
  nameList.Add('Dominique Dunne');
  nameList.Add('Irene Dunne');
  nameList.Add('Mildred Dunnock');
  nameList.Add('Kirsten Dunst');
  nameList.Add('Deanna Durbin');
  nameList.Add('Eliza Dushku');
  nameList.Add('Clea DuVall');
  nameList.Add('Jeanne Eagels');
  nameList.Add('Leslie Easterbrook');
  nameList.Add('Alison Eastwood');
  nameList.Add('Megalyn Echikunwoke');
  nameList.Add('Lisa Edelstein');
  nameList.Add('Barbara Eden');
  nameList.Add('Stacy Edwards');
  nameList.Add('Nicole Eggert');
  nameList.Add('Jill Eikenberry');
  nameList.Add('Carmen Electra');
  nameList.Add('Erika Eleniak');
  nameList.Add('Kimberly Elise');
  nameList.Add('Shannon Elizabeth');
  nameList.Add('Aunjanue Ellis');
  nameList.Add('Hope Emerson');
  nameList.Add('Jacqueline Emerson');
  nameList.Add('Jennifer Esposito');
  nameList.Add('Linda Evans');
  nameList.Add('Angie Everhart');
  nameList.Add('Morgan Fairchild');
  nameList.Add('Lola Falana');
  nameList.Add('Siobhan Fallon');
  nameList.Add('Dakota Fanning');
  nameList.Add('Elle Fanning');
  nameList.Add('Anna Faris');
  nameList.Add('Frances Farmer');
  nameList.Add('Vera Farmiga');
  nameList.Add('Terry Farrell');
  nameList.Add('Mia Farrow');
  nameList.Add('Farrah Fawcett');
  nameList.Add('Sherilyn Fenn');
  nameList.Add('America Ferrera');
  nameList.Add('Tina Fey');
  nameList.Add('Sally Field');
  nameList.Add('Linda Fiorentino');
  nameList.Add('Jenna Fischer');
  nameList.Add('Carrie Fisher');
  nameList.Add('Isla Fisher');
  nameList.Add('Joely Fisher');
  nameList.Add('Schuyler Fisk');
  nameList.Add('Zelda Fitzgerald');
  nameList.Add('Jennifer Flavin');
  nameList.Add('Rhonda Fleming');
  nameList.Add('Louise Fletcher');
  nameList.Add('Calista Flockhart');
  nameList.Add('Nina Foch');
  nameList.Add('Bridget Fonda');
  nameList.Add('Jane Fonda');
  nameList.Add('Joan Fontaine');
  nameList.Add('Deborah Foreman');
  nameList.Add('Jodie Foster');
  nameList.Add('Sara Foster');
  nameList.Add('Sutton Foster');
  nameList.Add('Megan Fox');
  nameList.Add('Vivica A. Fox');
  nameList.Add('Bonnie Franklin');
  nameList.Add('Diane Franklin');
  nameList.Add('Kate French');
  nameList.Add('Lindsay Frost');
  nameList.Add('Isabelle Fuhrman');
  nameList.Add('Annette Funicello');
  nameList.Add('Bethany Joy Galeotti');
  nameList.Add('Ava Gardner');
  nameList.Add('Judy Garland');
  nameList.Add('Jennifer Garner');
  nameList.Add('Peggy Ann Garner');
  nameList.Add('Janeane Garofalo');
  nameList.Add('Teri Garr');
  nameList.Add('Greer Garson');
  nameList.Add('Ana Gasteyer');
  nameList.Add('Janina Gavankar');
  nameList.Add('Erica Gavin');
  nameList.Add('Rebecca Gayheart');
  nameList.Add('Janet Gaynor');
  nameList.Add('Mitzi Gaynor');
  nameList.Add('Sarah Michelle Gellar');
  nameList.Add('Gladys George');
  nameList.Add('Gina Gershon');
  nameList.Add('Jami Gertz');
  nameList.Add('Debbie Gibson');
  nameList.Add('Melissa Gilbert');
  nameList.Add('Sara Gilbert');
  nameList.Add('Annabeth Gish');
  nameList.Add('Dorothy Gish');
  nameList.Add('Lillian Gish');
  nameList.Add('Robin Givens');
  nameList.Add('Summer Glau');
  nameList.Add('Paulette Goddard');
  nameList.Add('Tracey Gold');
  nameList.Add('Whoopi Goldberg');
  nameList.Add('Selena Gomez');
  nameList.Add('Ginnifer Goodwin');
  nameList.Add('Megan Good');
  nameList.Add('Ruth Gordon');
  nameList.Add('Betty Grable');
  nameList.Add('Maggie Grace');
  nameList.Add('Aimee Graham');
  nameList.Add('Heather Graham');
  nameList.Add('Lauren Graham');
  nameList.Add('Gloria Grahame');
  nameList.Add('Lee Grant');
  nameList.Add('Bonita Granville');
  nameList.Add('Erin Gray');
  nameList.Add('Ashley Greene');
  nameList.Add('Jennifer Grey');
  nameList.Add('Virginia Grey');
  nameList.Add('Judy Greer');
  nameList.Add('Pam Grier');
  nameList.Add('Corinne Griffith');
  nameList.Add('Melanie Griffith');
  nameList.Add('Leslie Grossman');
  nameList.Add('Carla Gugino');
  nameList.Add('Grace Gummer');
  nameList.Add('Mamie Gummer');
  nameList.Add('Jasmine Guy');
  nameList.Add('Maggie Gyllenhaal');
  nameList.Add('Shelley Hack');
  nameList.Add('Joan Hackett');
  nameList.Add('Jean Hagen');
  nameList.Add('Lucy Hale');
  nameList.Add('Grayson Hall');
  nameList.Add('Veronica Hamel');
  nameList.Add('Linda Hamilton');
  nameList.Add('Margaret Hamilton');
  nameList.Add('Daryl Hannah');
  nameList.Add('Alyson Hannigan');
  nameList.Add('Marcia Gay Harden');
  nameList.Add('Melora Hardin');
  nameList.Add('Ann Harding');
  nameList.Add('Mariska Hargitay');
  nameList.Add('Jean Harlow');
  nameList.Add('Angie Harmon');
  nameList.Add('Tess Harper');
  nameList.Add('Barbara Harris');
  nameList.Add('Danielle Harris');
  nameList.Add('Danneel Harris');
  nameList.Add('Julie Harris');
  nameList.Add('Rachael Harris');
  nameList.Add('Harriet Sansom Harris');
  nameList.Add('Linda Harrison');
  nameList.Add('Mariette Hartley');
  nameList.Add('Elizabeth Hartman');
  nameList.Add('Teri Hatcher');
  nameList.Add('Anne Hathaway');
  nameList.Add('Aaliyah Haughton');
  nameList.Add('Wanda Hawley');
  nameList.Add('Goldie Hawn');
  nameList.Add('Salma Hayek');
  nameList.Add('Helen Hayes');
  nameList.Add('Susan Hayward');
  nameList.Add('Rita Hayworth');
  nameList.Add('Glenne Headly');
  nameList.Add('Amber Heard');
  nameList.Add('Patricia Heaton');
  nameList.Add('Anne Heche');
  nameList.Add('Eileen Heckart');
  nameList.Add('Tippi Hedren');
  nameList.Add('Katherine Heigl');
  nameList.Add('Marg Helgenberger');
  nameList.Add('Mariel Hemingway');
  nameList.Add('Florence Henderson');
  nameList.Add('Christina Hendricks');
  nameList.Add('Marilu Henner');
  nameList.Add('Pamela Hensley');
  nameList.Add('Taraji P. Henson');
  nameList.Add('Katharine Hepburn');
  nameList.Add('Barbara Hershey');
  nameList.Add('Lori Heuring');
  nameList.Add('Jennifer Love Hewitt');
  nameList.Add('Catherine Hicks');
  nameList.Add('Paris Hilton');
  nameList.Add('Nichole Hiltz');
  nameList.Add('Cheryl Hines');
  nameList.Add('Connie Hines');
  nameList.Add('Gaby Hoffmann');
  nameList.Add('Alexandra Holden');
  nameList.Add('Judy Holliday');
  nameList.Add('Laurel Holloman');
  nameList.Add('Lauren Holly');
  nameList.Add('Celeste Holm');
  nameList.Add('Katie Holmes');
  nameList.Add('Miriam Hopkins');
  nameList.Add('Hedda Hopper');
  nameList.Add('Lena Horne');
  nameList.Add('Whitney Houston');
end;

procedure TFrmMain.PrintHeader;
begin
  RSPrint.WriteFont(1,  1, 'Report Example',[Bold]);
  RSPrint.WriteFont(1, 72, Format('Page: %2.2d', [RSPrint.PageNo]), [Bold]);
  RSPrint.Write(2,  1, StringOfChar('-', 80));

  RSPrint.Write(3,  1, 'ID');
  RSPrint.Write(3, 10, 'Name');
  RSPrint.Write(4,  1, StringOfChar('-', 80));
end;

end.
